version: '3.8'

services:
  jackett:
    container_name: jackett
    image: ghcr.io/hotio/jackett
    restart: unless-stopped
    network_mode: bridge
    ports:
    - "9117:9117"
    environment:
    - PUID=1000
    - PGID=1000
    - UMASK=002
    - TZ=${TZ}
    volumes:
    - /{config}/jackett:/config

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
    - "8989:8989"
    environment:
    - PUID=1000
    - PGID=1000
    - UMASK=002
    - TZ=<TZ>
    volumes:
    - /${config}/sonarr:/config
    - /${share}/sonarr:/data


  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    restart: unless-stopped
    network_mode: bridge
    ports:
    - "9696:9696"
    environment:
    - PUID=1000
    - PGID=1000
    - UMASK=002
    - TZ=${TZ}
    volumes:
    - /${config}/prowlarr:/config

  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    restart: unless-stopped
    network_mode: bridge
    ports:
    - "8080:8080"
    environment:
    - PUID=1000
    - PGID=1000
    - UMASK=002
    - TZ=${TZ}
    - WEBUI_PORTS=8080/tcp,8080/udp
    volumes:
    - /${config}/qbittorrent:/config
    - /${share}/qbittorrent:/data

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    restart: unless-stopped
    network_mode: bridge
    ports:
    - 9091:9091
    - 51413:51413
    - 51413:51413/udp
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=${TZ}
    - TRANSMISSION_WEB_HOME= #optional
    - USER= ${user_transmission}
    - PASS= ${pass_transmission}
    # - WHITELIST= #optional
    # - PEERPORT= #optional
    # - HOST_WHITELIST= #optional
    volumes:
    - /${config}/transmission:/config
    - /${share}/transmission_download:/downloads
    - /${share}/transmission_media}:/watch	  

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    network_mode: bridge
    ports:
    - "7878:7878"
    environment:
    - PUID=1000
    - PGID=1000
    - UMASK=002
    - TZ=${TZ}
    volumes:
    - /${config}/radarr:/config
    - /${share}/$radarr:/data

  xteve:
    container_name: xteve
    image: dnsforge/xteve
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "34400:34400"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - XTEVE_PORT=8080
      - XTEVE_BRANCH=master
      - XTEVE_DEBUG=0
      - XTEVE_API=1
      - GUIDE2GO_SERVER_HOST=10.0.0.1
      - GUIDE2GO_SERVER_PORT=31337
    volumes:
      - /${config}/xteve:/home/xteve/conf

  overseerr:
    container_name: overseerr
    image: ghcr.io/hotio/overseerr
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "5055:5055"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${TZ}
    volumes:
      - /${config}/overseerr:/config