version: '3.8'

services:
  jackett:
    container_name: jackett
    image: ghcr.io/hotio/jackett
    restart: unless-stopped
    network_mode: bridge
    ports:
    - "9117:9117"
    environment:
    - PUID=${PUID:-1000}
    - PGID=${PGID:-1000}
    - UMASK=${UMASK}
    - TZ=${TZ}
    - AUTO_UPDATE=true
    volumes:
    - /${config}/jackett:/config

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
    - "8989:8989"
    environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - UMASK=${UMASK}
    - TZ=<TZ>
    volumes:
    - /${config}/sonarr:/config
    - /${share}/sonarr:/data


  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    restart: unless-stopped
    network_mode: bridge
    ports:
    - "9696:9696"
    environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - UMASK=${UMASK}
    - TZ=${TZ}
    volumes:
    - /${config}/prowlarr:/config

  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent
    restart: unless-stopped
    network_mode: bridge
    ports:
    - "8080:8080"
    - "6881:6881"
    environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - UMASK=${UMASK}
    - TZ=${TZ}
    - WEBUI_PORTS=8080/tcp,8080/udp
    volumes:
    - /${config}:/config
    - /${share}/qbittorrent:/data
    - /${share}:/download

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    restart: unless-stopped
    network_mode: bridge
    ports:
    - 9091:9091
    - 51413:51413
    - 51413:51413/udp
    environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - UMASK=${UMASK}
    - TZ=${TZ}
    - TRANSMISSION_WEB_HOME= #optional
    - USER=${user}
    - PASS=${pass}
    # - WHITELIST= #optional
    # - PEERPORT= #optional
    # - HOST_WHITELIST= #optional
    volumes:
    - /${config}/transmission:/config
    - /${share}/transmission_download:/downloads
    - /${share}:/watch

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    network_mode: bridge
    ports:
    - "7878:7878"
    environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - UMASK=${UMASK}
    - TZ=${TZ}
    volumes:
    - /${config}/radarr:/config
    - /${share}/movies:/data

  xteve:
    container_name: xteve
    image: alturismo/xteve
    restart: unless-stopped
    network_mode: bridge
    ports:
    - "34400:34400"
    environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - UMASK=${UMASK}
    - TZ=${TZ}
    - XTEVE_PORT=8080
    - XTEVE_BRANCH=master
    - XTEVE_DEBUG=0
    - XTEVE_API=1
    - GUIDE2GO_SERVER_HOST=127.0.0.1
    - GUIDE2GO_SERVER_PORT=31337
    volumes:
    - /${config}/xteve:/home/xteve/conf
    - /${share}/xteve/m3u:/home/xteve/m3u
    - /${share}/xteve/xmltv:/home/xteve/xmltv

  overseerr:
    container_name: overseerr
    image: ghcr.io/hotio/overseerr
    restart: unless-stopped
    network_mode: bridge
    ports:
    - "5055:5055"
    environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - UMASK=${UMASK}
    - TZ=${TZ}
    volumes:
    - /${config}/overseerr:/config

  deluge:
    container_name: deluge
    image: linuxserver/deluge
    restart: unless-stopped
    network_mode: bridge
    ports:
    - "8112:8112"  # P ort pour accéder à l'interface Web de Deluge
    - "58846:58846"  # Port pour accéder à l'interface Deluge RPC
    environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - UMASK=${UMASK}
    - TZ=${TZ}
    volumes:
    - /${config}/deluge:/config     # Dossier de configuration de Deluge
    - /${share}/deluge:/downloads   # Dossier des torrents et données

  flaresolverr:
    container_name: flaresolverr
    image: flaresolverr/flaresolverr:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
    - "8191:8191"
    - "8192:8192"
    environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - UMASK=${UMASK}
    - TZ=${TZ}
    - LOG_LEVEL=info
    volumes:
    - /${config}/flaresolverr/config:/config

#  gluetun:
#    container_name: gluetun
#    image: qmcgaw/gluetun
#    restart: unless-stopped
#    cap_add:
#      - NET_ADMIN
#    environment:
#    - PUID=${PUID}
#    - PGID=${PGID}
#    - UMASK=${UMASK}
#    - TZ=${TZ}
#    - VPN_SERVICE_PROVIDER=airvpn
#    - VPN_TYPE=wireguard
#    - WIREGUARD_PRIVATE_KEY=XXX
#    - WIREGUARD_PRESHARED_KEY=XXX
#    - WIREGUARD_ADDRESSES=000.000.000.000/00
#    - FIREWALL_VPN_INPUT_PORTS=00000
#    - WIREGUARD_IMPLEMENTATION=auto
#    volumes:
#    - /${config}/gluetun:/gluetun
#    devices:
#      - /dev/net/tun:/dev/net/tun

